Upgrade to wasmer 1.0.1 and add in-memory cache
bandprotocol/owasm pull request #1
Opened 2021-02-03 02:19 UTC by thebevrishot

## Implementation details
- Upgrade wasmer to 1.0.1
- Implement in-memory caching for compiled module but we would not manage it here, we allow API callers (e.g. `go-owasm`) and pass it with code.

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-02-03 08:40 UTC, taobun requested changes

2021-02-03 08:40 UTC, taobun commented on src/core/vm.rs
> +        self.gas_used >= self.gas_limit
Should be `>` ?

2021-02-03 08:40 UTC, taobun commented on src/core/cache.rs
> +    pub fn store(&mut self, checksum: &Checksum, module: &Module) -> Result<(), Error> {
module should be `Module` (store should be the ownership of this clone inside function seems to be the wrong pattern)

2021-02-03 08:40 UTC, taobun commented on src/core/cache.rs
> +    pub fn store(&mut self, checksum: &Checksum, module: &Module) -> Result<(), Error> {
I think our code base didn't use VmResult coding style, so Don't return Result if it don't want to return error

2021-02-03 08:40 UTC, taobun commented on src/core/cache.rs
> +    pub fn load(&mut self, checksum: &Checksum) -> Result<Option<Module>, Error> {
Like this it should just return Option<Module> until we bring the Result coding

2021-02-24 11:54 UTC, Benzbeeb approved these changes

2021-02-24 11:55 UTC, merged