Gas metering
bandprotocol/owasm pull request #10
Opened 2022-08-25 10:18 UTC by colmazia

Fixed: update gas metering

## Implementation details
- update owasm gas metering to use wasmer middleware
- remove old gas metering
- update wasmer to 2.3.0
- **comment out vrf as gmp lib has som issues

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2022-08-26 06:51 UTC, RogerKSI requested changes

2022-08-26 06:51 UTC, RogerKSI commented on packages/vm/src/lib.rs
> +// fn inject_gas(module: Module) -> Result<Module, Error> {
please remove it. think we don't need it anymore.

2022-08-26 06:51 UTC, RogerKSI commented on packages/vm/src/vm.rs
> +    pub fn decrease_gas_left(&self, gas_used: u32) -> Result<(), Error> {
Currently, we use u64 for gas. Can we use u64 for gas_used?

2022-08-26 06:51 UTC, RogerKSI commented on packages/vm/src/lib.rs
> +            "gas" => Function::new_native_with_env(&store, owasm_env.clone(), |_env: &Environment<E>, _gas: u32| {
please add env.decrease_gas_left(1) here

2022-08-30 08:58 UTC, RogerKSI approved these changes

2022-08-31 07:22 UTC, RogerKSI requested changes

2022-08-31 07:22 UTC, RogerKSI commented on packages/vm/src/lib.rs
> +// use owasm_crypto::ecvrf;
please remove "env.ecvrf_verify" in SUPPORTED_IMPORTS.

2022-08-31 18:48 UTC, RogerKSI requested changes

2022-08-31 18:48 UTC, RogerKSI commented on packages/vm/src/vm.rs
> +    pub fn with_wasmer_instance<C, R>(&self, callback: C) -> VmResult<R>
please use our own result and error.

2022-08-31 18:48 UTC, RogerKSI commented on packages/vm/Cargo.toml
>  cosmwasm-vm = "0.13.2"
Can we upgrade the version?

2022-09-01 04:57 UTC, colmazia commented on packages/vm/src/vm.rs
> +    pub fn with_wasmer_instance<C, R>(&self, callback: C) -> VmResult<R>
Will be fixed in refactor

2022-09-01 04:57 UTC, colmazia commented on packages/vm/Cargo.toml
>  cosmwasm-vm = "0.13.2"
Will be fixed in refactor

2022-09-02 03:47 UTC, taobun commented on packages/vm/src/vm.rs
> +    pub fn decrease_gas_left(&self, gas_used: u64) -> Result<(), Error> {
rename `gas_used` to `gas`

2022-09-02 04:33 UTC, RogerKSI approved these changes

2022-09-02 08:38 UTC, taobun approved these changes

2022-09-02 08:38 UTC, merged