Refactor
bandprotocol/owasm pull request #12
Opened 2022-09-01 10:52 UTC by colmazia

Fixed: refactor owasm

## Implementation details
- separate compile section into compile.rs
- separate run function into calls.rs
- separate store section into store.rs
- separate import function into imports.rs
- convert anonymous import functions 
- create our own checksum so we don't have to import cosmwasm-vm
- add more unit test for all files

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2022-09-09 18:47 UTC, RogerKSI requested changes

2022-09-09 18:47 UTC, RogerKSI commented on packages/vm/src/compile.rs
> +    // pwasm_utils::stack_height::inject_limiter(module, MAX_STACK_HEIGHT)
please remove the comment.

2022-09-09 18:47 UTC, RogerKSI commented on packages/vm/src/error.rs
> +    ChecksumLengthNotMatch = 16, // Checksum not of intended length.
What do you mean by "not of"?

2022-09-12 10:56 UTC, taobun approved these changes

2022-09-12 12:38 UTC, RogerKSI approved these changes

2022-09-13 05:01 UTC, merged