update median
bandprotocol/owasm pull request #21
Opened 2022-11-08 14:18 UTC by warittornc

## Implementation details

- Change `median()` function into `median_integer()` and `median_float()`
- Modify `median_by()` to use `NumCast` instead of `T::one() + T::one()`

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2022-11-09 04:30 UTC, taobun approved these changes

2022-11-11 06:56 UTC, RogerKSI requested changes

2022-11-11 06:56 UTC, RogerKSI commented on packages/kit/Cargo.toml
>  version = "0.2.2"
should we update the version of the package as well? as it breaks the old function.

2022-11-14 06:52 UTC, RogerKSI approved these changes

2022-11-14 07:05 UTC, merged